/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafica.viste;

/**
 *
 * @author Marco La Salvia
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        super.setTitle("Rooming");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PannelloSinistro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PannelloDestro = new javax.swing.JPanel();
        emailLabel = new javax.swing.JLabel();
        separatoreMailPass = new javax.swing.JSeparator();
        passwordLabel = new javax.swing.JLabel();
        eMailTextField1 = new javax.swing.JTextField();
        separatoreMailPass1 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        emailLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PannelloSinistro.setBackground(new java.awt.Color(32, 33, 35));
        PannelloSinistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/immagini/logo.png"))); // NOI18N
        PannelloSinistro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 4, 610, 690));

        PannelloDestro.setBackground(new java.awt.Color(32, 33, 35));
        PannelloDestro.setForeground(null);
        PannelloDestro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailLabel.setFont(new java.awt.Font("Monospaced", 1, 19)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(34, 139, 34));
        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailLabel.setText("OPPURE...");
        PannelloDestro.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 110, 40));

        separatoreMailPass.setForeground(null);
        PannelloDestro.add(separatoreMailPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 430, 20));

        passwordLabel.setFont(new java.awt.Font("Monospaced", 1, 19)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(34, 139, 34));
        passwordLabel.setText("PASSWORD");
        passwordLabel.setMaximumSize(new java.awt.Dimension(66, 26));
        passwordLabel.setMinimumSize(new java.awt.Dimension(66, 26));
        PannelloDestro.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 100, 30));

        eMailTextField1.setCaretColor(new java.awt.Color(255, 255, 255));
        eMailTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eMailTextField1ActionPerformed(evt);
            }
        });
        PannelloDestro.add(eMailTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 430, 30));

        separatoreMailPass1.setForeground(null);
        PannelloDestro.add(separatoreMailPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 430, 10));
        PannelloDestro.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 430, 30));

        jButton2.setBackground(new java.awt.Color(34, 139, 34));
        jButton2.setFont(new java.awt.Font("Monospaced", 1, 19)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CERCA UN APPARTAMENTO");
        jButton2.setBorder(null);
        PannelloDestro.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 430, 40));

        emailLabel1.setFont(new java.awt.Font("Monospaced", 1, 19)); // NOI18N
        emailLabel1.setForeground(new java.awt.Color(34, 139, 34));
        emailLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailLabel1.setText("E-MAIL");
        PannelloDestro.add(emailLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 80, 40));

        jButton4.setBackground(new java.awt.Color(34, 139, 34));
        jButton4.setFont(new java.awt.Font("Monospaced", 1, 19)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("LOGIN");
        jButton4.setBorder(null);
        PannelloDestro.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 430, 40));

        jButton5.setBackground(new java.awt.Color(34, 139, 34));
        jButton5.setFont(new java.awt.Font("Monospaced", 1, 19)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("REGISTRATI");
        jButton5.setBorder(null);
        PannelloDestro.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 430, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PannelloSinistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PannelloDestro, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PannelloSinistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PannelloDestro, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        PannelloDestro.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eMailTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eMailTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eMailTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PannelloDestro;
    private javax.swing.JPanel PannelloSinistro;
    private javax.swing.JTextField eMailTextField1;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JSeparator separatoreMailPass;
    private javax.swing.JSeparator separatoreMailPass1;
    // End of variables declaration//GEN-END:variables
}
