/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProfiloUtente;

/**
 *
 * @author Delbo
 */
public enum Nazione {
    NORVEGIA, SVEZIA, FINLANDIA, RUSSIA, ESTONIA, LETTONIA, LITUANIA, KAZAKISTAN,
    DANIMARCA, POLONIA, BIELORUSSIA, UCRAINA, IRLANDA, REGNO_UNITO, PAESI_BASSI,
    BELGIO, GERMANIA, REPUBBLICA_CECA, SLOVACCHIA, ROMANIA, MOLDAVIA, GEORGIA, AZERBAIGIAN,
    ARMENIA, FRANCIA, SVIZZERA, SLOVENIA, CROAZIA, BOSNIA, SERBIA, BULGARIA, MACEDONIA,
    ALBANIA, GRECIA, ITALIA, PORTOGALLO, SPAGNA, TURCHIA, SIRIA, IRAQ, CIPRO, LIBANO, GIORDANIA,
    ARABIA_SAUDITA, ISRAELE, MYANMAR, TUNISIA, ALGERIA, MAROCCO, AFRICA, ALTRO, AUSTRALIA, AMERICA, CANADA,
    ARGENTINA, CINA, GIAPPONE, FILIPPINE
    
}
